services:
  db:
    image: postgres:18
    container_name: db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
    - "${DB_PORT}:5432"
    volumes:
      - dbdata:/var/lib/postgresql
    networks:
      - app-network

  api:
    build:
      context: ./app/api
      dockerfile: Dockerfile
    container_name: api
    restart: always
    env_file:
      - .env
    environment:
      ASPNETCORE_ENVIRONMENT: ${ASPNETCORE_ENVIRONMENT}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      JWT_ISSUER: ${JWT_ISSUER}
      JWT_AUDIENCE: ${JWT_AUDIENCE}
      JWT_SECRET: ${JWT_SECRET}
    expose:
      - "5000"
    depends_on:
      - db
    networks:
      - app-network

  web:
    build:
      context: ./app/web
      dockerfile: Dockerfile
      args:
        API_BASE_URL: ${API_BASE_URL}
    container_name: web
    restart: always
    env_file:
      - .env
    environment:
      API_BASE_URL: ${API_BASE_URL}
    ports:
      - "${WEB_PORT}:3000"
    depends_on:
      - api
    networks:
      - app-network


volumes:
  dbdata:

networks:
  app-network:
