services:
  db:
    image: postgres:18
    container_name: db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER:-user}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-password}
      POSTGRES_DB: ${DB_NAME:-db}
    ports:
    - "${DB_PORT:-5432}:5432"
    volumes:
      - dbdata:/var/lib/postgresql
    networks:
      - app-network

  api:
    build:
      context: ./app/api
      dockerfile: Dockerfile
    container_name: api
    restart: always

    env_file:
      - .env
    ports:
      - "${API_PORT:-5000}:5000"
    depends_on:
      - db
    networks:
      - app-network

  web:
    build:
      context: ./app/web
      dockerfile: Dockerfile
    container_name: web
    restart: always
    env_file:
      - .env
    ports:
      - "${WEB_PORT:-3000}:3000"
    depends_on:
      - api
    networks:
      - app-network


volumes:
  dbdata:

networks:
  app-network:
